### ISSUE TITLE
Create a protocol to update R and Python versions

### ISSUE THREAD

**Issue by JoaoCarabetta** [ipeaGIT/geobr#141]
Soon, Python and R version are going to have the same functions. But, we need to figure out a protocol to make sure that both versions keep having the same functions, defaults and basic functionalities. (I already don't know what changes you've done in recent weeks to already implemented functions)

My proposal is to create a file that has the metadata about all functions (similar to the README table). This'd be the table that specifies what are the arguments, defaults and functions in place. 

Example:

```yaml
read_functions:
    - name: read_municipality
      source: IBGE
      short_description: Download shape files of Brazilian municipalities as sf objects.
      full_description: Data at scale 1:250,000, using Geodetic reference system "SIRGAS2000" and CRS(4674)
      args:
           - name: code_muni
             default: 'all'
           - name: year
             default: 2010
             available: [1872, 1900, 1911, 1920, 1933, 1940, 1950, 1960, 1970, 1980, 1991, 2000, 2001, 2005, 2007, 2010, 2013, 2014, 2015, 2016, 2017, 2018]
           - simplified: True      
    - name: read_amazon
      source: MMA
      short_description: Download official data of Brazil's Legal Amazon as an sf object.
      full_description: This data set covers the whole of Brazil's Legal Amazon as defined in the federal law n. 12.651/2012). The original data comes from the Brazilian Ministry of Environment (MMA) and can be found at http://mapas.mma.gov.br/i3geo/datadownload.htm .
       args:
           - name: year
             default: 2012
             available: [2012]
           - simplified: True           
```

We have several options on how to build this file and updated it:
1. Updated it manually every time a function is added or updated. Python branch has to keep track of the changes and apply the changes manually.
2. Scrap the R functions to create the file automatically. Also scrap Python functions to create a similar file. Do a diff and find what has changed.
3. Scrap the R functions to create the file automatically. Python functions are parametrized with this file. So, every R change, updates Python functions automatically.
4. File is updated manually, but R and Python functions are parametrized to be updated with this file.

Let me know what you all think.
